name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: self-hosted
    strategy:
      matrix:
        build:
          - name: data-transport-layer
            file: ./ops/docker/Dockerfile.packages
            target: data-transport-layer
            args: NODE_OPTIONS=--max-old-space-size=6144
          - name: message-relayer
            file: ./ops/docker/Dockerfile.packages
            target: message-relayer
            args: NODE_OPTIONS=--max-old-space-size=6144
          - name: l2geth
            file: ./l2geth/Dockerfile
            target: ''
            args: ''
          - name: batch-submitter
            file: ./ops/docker/Dockerfile.batch-submitter-service
            args: ''
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.build.file }}
          target: ${{ matrix.build.target }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ matrix.build.name }}:${{ github.ref_name }}
          build-args: ${{ matrix.build.args }}
          push: true
